#!/usr/bin/env bash

echo "x     f(x)"
echo "------------"

for n in {1..10}
do
	x=$(printf '%s\n' "scale=20; -3 - 10^(-$n)" | bc -l)
	fx=$(printf '%s\n' "scale=20; ($x^2 - 9) / ($x + 3)" | bc -l)
	printf "%.5f     %.10f\n" "$x" "$fx"
done