#!/bin/sh

printf '%-10s %-16s %-20s\n' 'Iteration' 'x (below 1)' 'F(x)'
printf '%-10s %-16s %-20s\n' '---------' '----------------' '--------------------'

awk '
BEGIN {
	for (iteration = 1; iteration <= 10; iteration++) {
		delta = 10^(-iteration)
		x = 1 - delta
		value = x^(1 / (1 - x))
		printf "%-10d %-16.10f %-20.12f\n", iteration, x, value
	}
}
'

printf '\n%-10s %-16s %-20s\n' 'Iteration' 'x (above 1)' 'F(x)'
printf '%-10s %-16s %-20s\n' '---------' '----------------' '--------------------'

awk '
BEGIN {
	for (iteration = 1; iteration <= 10; iteration++) {
		delta = 10^(-iteration)
		x = 1 + delta
		value = x^(1 / (1 - x))
		printf "%-10d %-16.10f %-20.12f\n", iteration, x, value
	}
}
'
